# Generated by Django 5.2.13 on 2026-04-24 15:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rma_number", models.CharField(max_length=30, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("not_as_described", "Not as Described"),
                            ("damaged", "Damaged on Arrival"),
                            ("wrong_item", "Wrong Item Sent"),
                            ("changed_mind", "Changed Mind"),
                            ("faulty", "Faulty / Defective"),
                            ("not_received", "Not Received"),
                            ("duplicate_order", "Duplicate Order"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("awaiting_return", "Awaiting Return"),
                            ("received", "Item Received"),
                            ("inspected", "Inspected"),
                            ("refunded", "Refunded"),
                            ("replacement_sent", "Replacement Sent"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        default="requested",
                        max_length=30,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("refund", "Full Refund"),
                            ("replacement", "Replacement"),
                            ("partial_refund", "Partial Refund"),
                            ("store_credit", "Store Credit"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("description", models.TextField()),
                ("customer_comments", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "return_tracking_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("return_received_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("condition", models.CharField(blank=True, max_length=50)),
                ("restock", models.BooleanField(default=False)),
            ],
        ),
    ]
