# Generated by Django 5.2.13 on 2026-04-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_number", models.CharField(max_length=20, unique=True)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("mobile", models.CharField(blank=True, max_length=30)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("retail", "Retail"),
                            ("wholesale", "Wholesale"),
                            ("marketplace", "Marketplace"),
                        ],
                        default="retail",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_hold", "On Hold"),
                            ("blacklisted", "Blacklisted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("prepay", "Prepayment"),
                            ("net7", "Net 7 Days"),
                            ("net14", "Net 14 Days"),
                            ("net30", "Net 30 Days"),
                            ("net60", "Net 60 Days"),
                            ("eom", "End of Month"),
                            ("other", "Other"),
                        ],
                        default="prepay",
                        max_length=20,
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("tax_exempt", models.BooleanField(default=False)),
                ("vat_number", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["company_name", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("billing", "Billing"),
                            ("shipping", "Shipping"),
                            ("both", "Billing & Shipping"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("postcode", models.CharField(max_length=20)),
                ("country", models.CharField(default="United Kingdom", max_length=100)),
            ],
            options={
                "ordering": ["-is_default", "address_type"],
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_important", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
