# Generated by Django 5.2.13 on 2026-04-25 14:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptitem",
            name="qc_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceiptitem",
            name="qc_checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qc_checked_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptitem",
            name="qc_fail_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="goodsreceiptitem",
            name="qc_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="goodsreceiptitem",
            name="qc_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending QC"),
                    ("passed", "Passed QC"),
                    ("failed", "Failed QC"),
                    ("quarantined", "Quarantined"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1.000000"),
                help_text="Exchange rate to GBP at time of order",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="freight_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="import_duty",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="other_charges",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="landed_unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calculated on receipt: unit_cost + prorated freight/duty/charges",
                max_digits=12,
                null=True,
            ),
        ),
    ]
