# Generated by Django 5.2.13 on 2026-04-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0002_initial"),
        ("sales", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_order_id", models.CharField(max_length=255)),
                ("external_order_number", models.CharField(blank=True, max_length=255)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Import"),
                            ("imported", "Imported"),
                            ("failed", "Import Failed"),
                            ("duplicate", "Duplicate"),
                            ("ignored", "Ignored"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_orders",
                        to="channels.channel",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketplace_source",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="channels_ma_status_b3274a_idx"
                    ),
                    models.Index(
                        fields=["channel", "status"],
                        name="channels_ma_channel_28ec3f_idx",
                    ),
                ],
                "unique_together": {("channel", "external_order_id")},
            },
        ),
    ]
