# Generated by Django 5.2.13 on 2026-04-24 15:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourierIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("lost", "Lost Parcel"),
                            ("damaged", "Damaged in Transit"),
                            ("delayed", "Delayed"),
                            ("failed_delivery", "Failed Delivery Attempt"),
                            ("wrong_address", "Wrong Address / Undeliverable"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("claim_submitted", "Claim Submitted"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("claim_reference", models.CharField(blank=True, max_length=100)),
                (
                    "compensation_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "courier",
                    models.CharField(
                        choices=[
                            ("evri", "Evri (Hermes)"),
                            ("royal_mail", "Royal Mail"),
                            ("dpd", "DPD"),
                            ("dhl", "DHL"),
                            ("ups", "UPS"),
                            ("fedex", "FedEx"),
                            ("yodel", "Yodel"),
                            ("parcelforce", "Parcelforce"),
                            ("other", "Other"),
                        ],
                        default="evri",
                        max_length=20,
                    ),
                ),
                ("service", models.CharField(blank=True, max_length=100)),
                (
                    "tracking_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("tracking_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("label_created", "Label Created"),
                            ("dispatched", "Dispatched"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("failed_delivery", "Failed Delivery"),
                            ("returned", "Returned to Sender"),
                            ("lost", "Lost / Missing"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("label_data", models.TextField(blank=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_delivery", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
