# Generated by Django 5.2.13 on 2026-04-24 15:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Note"),
                            ("customer", "Customer Communication"),
                            ("system", "System Event"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                (
                    "external_order_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("ebay", "eBay"),
                            ("amazon", "Amazon"),
                            ("woocommerce", "WooCommerce"),
                            ("direct", "Direct / Website"),
                            ("phone", "Phone / Email"),
                            ("wholesale", "Wholesale"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("awaiting_dispatch", "Awaiting Dispatch"),
                            ("dispatched", "Dispatched"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("on_hold", "On Hold"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partial", "Partial"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("disputed", "Disputed"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("ship_to_name", models.CharField(blank=True, max_length=255)),
                ("ship_to_company", models.CharField(blank=True, max_length=255)),
                ("ship_to_address1", models.CharField(blank=True, max_length=255)),
                ("ship_to_address2", models.CharField(blank=True, max_length=255)),
                ("ship_to_city", models.CharField(blank=True, max_length=100)),
                ("ship_to_county", models.CharField(blank=True, max_length=100)),
                ("ship_to_postcode", models.CharField(blank=True, max_length=20)),
                (
                    "ship_to_country",
                    models.CharField(default="United Kingdom", max_length=100),
                ),
                ("ship_to_phone", models.CharField(blank=True, max_length=30)),
                ("ship_to_email", models.EmailField(blank=True, max_length=254)),
                ("bill_to_name", models.CharField(blank=True, max_length=255)),
                ("bill_to_company", models.CharField(blank=True, max_length=255)),
                ("bill_to_address1", models.CharField(blank=True, max_length=255)),
                ("bill_to_city", models.CharField(blank=True, max_length=100)),
                ("bill_to_postcode", models.CharField(blank=True, max_length=20)),
                (
                    "bill_to_country",
                    models.CharField(default="United Kingdom", max_length=100),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("currency", models.CharField(default="GBP", max_length=3)),
                ("requested_delivery_date", models.DateField(blank=True, null=True)),
                ("dispatched_date", models.DateField(blank=True, null=True)),
                (
                    "marketplace_fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("marketplace_order_id", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("20.00"), max_digits=5
                    ),
                ),
                (
                    "buy_price_at_time",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
