# Generated by Django 5.2.13 on 2026-04-24 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_initial"),
        ("products", "0002_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ordernote",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="ordernote",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_notes",
                to="sales.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="sales.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["status"], name="sales_sales_status_480214_idx"),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["channel"], name="sales_sales_channel_9ba18e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["payment_status"], name="sales_sales_payment_54d85b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["created_at"], name="sales_sales_created_f48ee5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["customer"], name="sales_sales_custome_b24b56_idx"
            ),
        ),
    ]
