# Generated by Django 5.2.13 on 2026-04-24 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channellisting",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_listings",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="stocklevel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_levels",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="stocklevel",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_levels",
                to="products.stocklocation",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="products.stocklocation",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_pr_sku_ca0cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["barcode"], name="products_pr_barcode_e44f4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["status"], name="products_pr_status_041708_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="channellisting",
            unique_together={("product", "channel", "external_id")},
        ),
        migrations.AddIndex(
            model_name="stocklevel",
            index=models.Index(
                fields=["product", "location"], name="products_st_product_de4e55_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stocklevel",
            unique_together={("product", "location")},
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["product", "created_at"], name="products_st_product_a806c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="products_st_referen_03e101_idx",
            ),
        ),
    ]
