# Generated by Django 5.2.13 on 2026-04-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("abbreviation", models.CharField(max_length=10, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "base_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank if this is a base unit (e.g. Each)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_units",
                        to="products.unitofmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="purchase_uom",
            field=models.ForeignKey(
                blank=True,
                help_text="Unit used when ordering from supplier (e.g. Case, Pallet)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchased_products",
                to="products.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sale_uom",
            field=models.ForeignKey(
                blank=True,
                help_text="Unit used when selling to customers (e.g. Each)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sold_products",
                to="products.unitofmeasure",
            ),
        ),
        migrations.CreateModel(
            name="UoMConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="1 [from_uom] = [conversion_factor] [to_uom]",
                        max_digits=14,
                    ),
                ),
                (
                    "from_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions_from",
                        to="products.unitofmeasure",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for a global conversion applicable to all products",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uom_conversions",
                        to="products.product",
                    ),
                ),
                (
                    "to_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions_to",
                        to="products.unitofmeasure",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_uom", "to_uom", "product")},
            },
        ),
    ]
