# Generated by Django 5.2.13 on 2026-04-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_unitofmeasure_product_purchase_uom_product_sale_uom_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stocklocation",
            name="is_receiving_bay",
            field=models.BooleanField(
                default=False,
                help_text="Mark as the primary receiving/QC location for incoming goods",
            ),
        ),
    ]
